import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createAdminDeleteAccountHandler} from '../../api/admin-delete-account.mjs';
function fixture({invalidToken=false,admin=true,recent=true,blocked=false,deleteFailure=false}={}) {
 const docs=new Map([['users/target',{role:'provider'}],['users/admin',{role:'driver'}],['adminAccess/admin',{enabled:true,role:'super_admin'}],['providerDirectory/target',{online:true}]]),deleted=[],authDeleted=[];
 const snapshot=(path)=>({exists:docs.has(path),data:()=>docs.get(path)});
 const db={doc(path){return {path,get:async()=>snapshot(path),update:async d=>docs.set(path,{...docs.get(path),...d})};},collection(){return {where(){return {get:async()=>({docs:blocked?[{id:'job',data:()=>({status:'accepted'}),ref:{collection(){return {doc:()=>({get:async()=>({exists:false})})};}}}]:[]})};}};},runTransaction:async fn=>fn({get:async r=>snapshot(r.path),set:(r,d)=>docs.set(r.path,{...docs.get(r.path),...d})}),recursiveDelete:async r=>{if(deleteFailure)throw Error('temporary backend failure');deleted.push(r.path);docs.delete(r.path);}};
 const auth={verifyIdToken:async()=>{if(invalidToken)throw Error('expired');return {uid:'admin',admin,email_verified:true,auth_time:Date.now()/1000-(recent?0:1000)};},updateUser:async()=>{},revokeRefreshTokens:async()=>{},deleteUser:async uid=>authDeleted.push(uid)};
 const handler=createAdminDeleteAccountHandler({getServices:()=>({auth,db,timestamp:()=>1})});
 async function request({token=true,method='POST',body}={}){const res={setHeader(){},status(c){this.code=c;return this;},json(d){this.body=d;return this;},end(){return this;}};await handler({method,headers:token?{authorization:'Bearer test'}:{},body:body??{uid:'target',confirmation:'target',reason:'Dedicated test cleanup requested.'}},res);return res;}
 return {request,docs,deleted,authDeleted};
}
test('missing or expired sessions return 401 without mutation',async()=>{for(const invalidToken of [false,true]){const f=fixture({invalidToken});assert.equal((await f.request({token:invalidToken})).code,401);assert.equal(f.deleted.length,0);assert.equal(f.docs.has('accountModeration/target'),false);}});
test('only verified recently signed-in super admin can delete',async()=>{assert.equal((await fixture({admin:false}).request()).code,403);assert.equal((await fixture({recent:false}).request()).code,401);});
test('blocked deletion keeps target access and directory unchanged',async()=>{const f=fixture({blocked:true});assert.equal((await f.request()).code,409);assert.equal(f.docs.has('accountModeration/target'),false);assert.equal(f.docs.get('providerDirectory/target').online,true);assert.deepEqual(f.authDeleted,[]);});
test('permanent cleanup deletes only target data and Auth identity and keeps audit',async()=>{const f=fixture();assert.equal((await f.request()).code,200);assert.deepEqual(f.authDeleted,['target']);assert.deepEqual(f.deleted,['users/target','providerApplications/target','providerDirectory/target']);assert.equal(f.docs.get('adminAudit/deletion_target').state,'complete');assert.equal(f.docs.has('users/admin'),true);});
test('completed deletion can be retried safely',async()=>{const f=fixture();await f.request();assert.equal((await f.request()).code,200);assert.deepEqual(f.authDeleted,['target']);});
test('partial backend failure stays blocked for safe retry',async()=>{const f=fixture({deleteFailure:true});assert.equal((await f.request()).code,500);assert.equal(f.docs.get('adminAudit/deletion_target').state,'deleting');assert.equal(f.docs.get('accountModeration/target').status,'suspended');assert.deepEqual(f.authDeleted,[]);});
test('cannot delete own or enabled admin account or bypass confirmation',async()=>{const f=fixture();assert.equal((await f.request({body:{uid:'admin',confirmation:'admin',reason:'Do not delete active admin.'}})).code,409);assert.equal((await f.request({body:{uid:'target',confirmation:'other',reason:'Invalid confirmation attempt.'}})).code,400);assert.deepEqual(f.deleted,[]);});
